### PR TITLE
Feature/modules separation

### PR DESCRIPTION
**Pull request by OrdonTeam**

### CODE REVIEW

**Comment by jozzi05** [comment]
This still needs some love. For me app crashes when i'm trying to log in to debate.
```java
kotlin.NotImplementedError: An operation is not implemented.
  at pl.elpassion.elspace.common.ContextProvider$1.invoke(ContextProvider.kt:6)
  at pl.elpassion.elspace.common.ContextProvider$1.invoke(ContextProvider.kt:5)
```

**Comment by OrdonTeam** [comment]
Sure. It is because debate does not have Application class where
ContextPorvider should be initialized.

wt., 23 maj 2017 o 17:30 użytkownik Dominik <notifications@github.com>
napisał:

**Comment by jozzi05** [comment]
It would be nice to change modules names.

**Comment by pawegio** [comment]
`app` -> `el-debate`
`eldebate` -> `el-debate-app`
`elspace` -> `el-space-app`
❓

**Comment by OrdonTeam** [comment]
:+1:

śr., 24 maj 2017 o 11:03 użytkownik Paweł Gajda <notifications@github.com>
napisał:

**Comment by jozzi05** [comment]
Lgtm

**Comment by jozzi05** [comment]
Remove redundant resources from debate module

**Comment by jozzi05** [comment]
Check if previous styles are applied.

**Pull request merged**
